### ISSUE TITLE
Use platform independent standard paths

### ISSUE THREAD

**Issue by Calinou** [inexor-game/code#152]
Inexor should use the standard paths. The free desktop foundation provides a specification for standard paths on linux. Additionally we need to handle standard paths for other platforms as well. The Qt project provides a good overview.

* [Free desktop XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)
* [Qt standard paths](https://doc.qt.io/qt-5/qstandardpaths.html)

## Tasks

- [x] Make flex use XDG base directories (linux)
- [x] Make flex use the Qt standard paths (all platforms)
- [x] Ensure localized standard paths are handled correctly (`/home/user/Documents` vs. `/home/user/Dokumente`)

## Original Issue

The XDG paths would be, here:
- `~/.config/inexor` for configuration files,
- `~/.local/share/inexor` for data files like screenshots,
- `~/.cache/inexor` for cache files.

This requires some additional programming as there would be several paths.

**Comment by aschaeffer** [comment]
:+1:

**Comment by Fohlen** [comment]
Should be clarified once #108 is in charge and we build our own linux packages.

**Comment by FaTony** [comment]
Remember that these are not hardcoded but use XDG_* environment variables.

**Comment by Croydon** [comment]
Red Eclipse reference: https://github.com/red-eclipse/base/issues/572

**Comment by Fohlen** [comment]
This is already part of Inexor Flex! 👍

**Comment by a-teammate** [comment]
It's not yet done in the master branch is it?

**Comment by aschaeffer** [comment]
It's in master in flex, but unfortunately the nodejs module we are using only handles linux standard paths but not windows or mac os x. 

I've done a little research and found that the Qt project has a good summary for the standard paths for all platforms:

https://doc.qt.io/qt-5/qstandardpaths.html

**Comment by a-teammate** [comment]
There is a project which did try to port those to node.js:
https://www.npmjs.com/package/node-standardpaths

**Comment by Croydon** [comment]
https://github.com/inexor-game/flex/commit/fc9402137f463e557904ba3bc2c406b313f9a82b

**Comment by a-teammate** [comment]
Note:

On windows we do not want to use the stdpaths.
Even [German judges](https://www.lawblog.de/index.php/archives/2017/05/31/ein-richter-erklaert-das-internet-und-zwar-gut/) (sorry its German) currently ruled that the appdata path is no path any std user knows about.
So if we want to enforce standardpaths because that's a goal on GNU platforms. Go ahead: do so.
But plz not for windows users. They are not as romantic with their platform and generally less expertized in that.
Furthermore "integration" into a uniform fashion is a lesser goal on windows, while I hear it a lot from linux people.

So on windows:
Everything into "Documents/My Games" as most applications do it.
I do not think we should hide **anything** from the user in any places (just the tmp folder maybe).
I thought about it for a little and I would go as far as even putting screenshots into My Games instead of "Pictures".

**Comment by aschaeffer** [comment]
I'm sure that we don't want to repeat mistakes of others because they are used to. The windows people are not doing it because it's the right thing but because it's already a mess. We can contribute to the mess or be the first doing things right :-P

We'll make it configurable:
* "Use windows standard paths"
* "Use Documents/My Games"

And provide two profiles:
* default (uses standard paths)
* portable (use one folder for all)

During installation you'll get asked about which option you want.

That's already a thing I wanted to achieve with the profiles feature. Just not in the first step (make things work, then make it better).

Btw. the portable profile makes sense on linux, too. Think of snaps, flatpack and so on.

**Comment by a-teammate** [comment]
No, srsly thats the missunderstanding imo: its not because others are doing it wrong, its because they assume that people do not know their platform. :D

So instead of asking the user to know the routes

OS/cache_files/inexor
OS/picture_files/inexor
OS/.._files/inexor

they think its easier for the user to remember just **one** path:
`OS/My Games` and just search on from there.

Sure we could make it configurable, thats also good (for linux portable packages).
I doubt they are for windows, but hey .. why not? Still: the default should be the My Games one.

**Comment by aschaeffer** [comment]
With my suggestion that would be achieved by simply using the profile `portable`. I'm open to make this the default profile on the windows platform.

I'll create a new issue **Configure the paths using profiles and provide a profile for portable installations**

**Comment by a-teammate** [comment]
Imo the portable profile should really be self-contained in the install directory,
while `Documents/My Games` is a the standard path on windows for all game specific user files.

the portable profile still sounds good :)
