### ISSUE TITLE
Getting involved - Onboarding process.

### ISSUE THREAD

**Issue by MartinMuzatko** [inexor-game/code#300]
Currently, it is not that easy to get involved with the project. Especially via the website there is only little information on how to get involved NOW!

**How I got involved:**

1. found out about Inexor via people on Sauerbraten
2. Went to Inexor.org website - awesome! I want to be part of this!
3. Looked at the menu - uhm where are the contact infos?
4. Well, I'll click on "Team" that kinda sounds like "Contact" - nope! nothing
5. Went to Wiki - we leave the shiny website land - well what about FAQ? urm no - just tech stuff
6. How to get involved! that sounds great! *click*
7. That sounds great!  _Always helpful: Speak with the other Inexor people about your feature idea._
8. Finally get on IRC
9. Zirp Zirp - where is everybody?
10. Finally get noticed by a_teammate by furiously contributing issues
11. Geting invited to Mumble
12. Now we're talking! Have my first very exciting talk with a_teammate, nothing and Khorne. Awesome!
13. I'm involved now.

Sometimes you find people that are interested as I am. but people across the road will drop off. Also called conversion rate. I know that this speed bump could be intentional, as you only want interested people to contribute, but right now you make it pretty hard for anyone to contribute.

**How are we going to improve the process**
I'll write up additional contexts for the website that are required in order to have a great onboarding process to get involved.

**Todo:**

- [x] Make Contact more obvious to find on the main website
- [x] Make [Development Communication](https://github.com/inexor-game/code/wiki/Developing-Communication) the cornerstone of communication opportunities
- [x] Add a clear "Contact" Section to the wiki
- [x] Establish *preferred* ways of communication - what medium to use for what?
- [x] Establish *preferred* ways of collaboration - what medium to use for what?
- [x] [What can you do](https://github.com/inexor-game/code/wiki/How-To-Contribute-Code) while you wait for a talk with the devs?
- [x] Add "Beginner" Issue label to compile a list of things that can be solved easily by people new to the project.
- [x] Add information how and what to contribute in [How to contribute content](https://github.com/inexor-game/code/wiki/How-to-Contribute-Content)

I already added the contact section to the wiki to have a direct link to developing communication. Also I did some wiki gardening to fix broken links.

**Comment by Croydon** [comment]
I already had the same impression.
In addition to your suggestions I am thinking about creating a page, where people can select their skills/field of work they want to bring in with direct recommendations what they can work on as a result.

**Comment by MartinMuzatko** [comment]
Already dis that with the team/recruits page :)

**Comment by MartinMuzatko** [comment]
Thank you!
