### ISSUE TITLE
Refactor and document the entity system

### ISSUE THREAD

**Issue by IAmNotHanni** [inexor-game/code#322]
Hanack's entity system provides the basis for many other so called **subsystems**. Almost everything in the game can be considered to be an entity. The work seems to be done mostly, but it needs to be commented.
This will be a major breakthrough because many of these subsystems represent important parts of the game which can be rewritten so they have the same basis.

![Modules which will be based on the entity system](https://raw.githubusercontent.com/inexor-game/visualisations/e46489c64f4177c4574b1c66c084d311da1e907a/hanacks%20entity%20and%20particle%20system/entity_system_relationships.png)

I downloaded the entity and particle system from the **cef+ipc+entities+bezier** branch and included the files in **hanni/3DVisualScripting**.
I also resolved the **muParser dependency**.

I started reviewing and documenting it. In order to do so I created class digrams with Visual Studio.
See [this](https://github.com/inexor-game/visualisations/commit/45f342299fce76f3ea603c745da0cfbade201a85)

I think I need Hanack's help to truely understand it.
Once I did I will rewrite my curve engine and 3D Visual Scripting based on this code.
With this understanding I can go on and rewrite other modules of the game.
So everything will be based on that framework.

## TODO
- [ ] refactor and review Hanack's entity system
- [ ] create a full **documentation** of it 
- [ ] build the **particle system** on top of it (mostly done by Hanack already)
- [ ] improve the entity rendering/handling using Hanni's code
- [ ] build the **projectile and decal system** on top of the particle system
- [ ] build the **mapmodel system** on top of it
- [ ] build the **pickup system** on top of it
- [ ] build the **** on top of it
- [ ] build the curve engine (bezier/hermite..) on top of it
- [ ] build the 3D Visual Scripting System on top of it

**Comment by IAmNotHanni** [comment]
Ok Hanack and I just made it work on Linux! Yay!
https://github.com/inexor-game/code/commit/8685f1272afcea54daf83e10eb49ddce513ed9dd

**Comment by IAmNotHanni** [comment]
Good start:
https://github.com/inexor-game/code/commit/15ee0845529df3b3f259a21b82e0f31e7015683b

**Comment by Croydon** [comment]
When you have done "_create a full documentation of it_" and "_improve the entity rendering/handling using Hanni's code_" this should be closed since we have or should have individual issues for everything else.
