### ISSUE TITLE
Make Inexor capable to run multiple instances

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#362]
### Motivation

Making Inexor able to run multiple instances would mean we can start and stop servers and clients at runtime.

### Requirements

- [x] Separate Inexor Flex in it's own repository (#360)
- [x] Inexor Lifecycle (Initialising Inexor Tree, RPC and parsing command line options) (#354)
- [x] Define the default ports (#367)

### Architecture

In order to achieve multi instance capabilities, we have to redesign the architecture:

- [x] One instance of Inexor Flex manages 0..N instances of Inexor Core
  * Start an instance
  * Stop an instance
- [x] Only one instance of Inexor Flex is allowed
  * Starting Inexor Flex again will parse and execute the given command line commands (for example: `./inexor start client` starts a new instance of the Inexor Core Client)
- [x] Each instance of Inexor Core has an **instance id**
  * The instance id is the GRPC port
  * Passing the instance id as command line option

### Inexor Tree

- [x] Inexor Flex manages the overall Inexor Tree
- [x] For each instance of Inexor Core a sub tree is created
  * The sub tree is initialized before an instance of Inexor Core is started
  * The path of the sub tree starts with the _instance id_
  * The REST urls contains the _instance id_

### User Interface (HUD / Application) for Inexor Core (Client) instances

* Inexor Flex provides the user interface for all instances of Inexor Core
* Each REST request must contain the _instance id_

### Inexor Flex Business Logic

* A lot of services can be shared across all instances:
  * InexorTree REST API (_instance id_)
  * TextureManager
  * ServerListManager
* Other services have to be created for each instance of Inexor Core:
  * Game State
  * Game Mode

### Future

* Inexor Core (Server): Server Management
  * Inexor Flex provides a web Interface
    * Create a new server instance
    * Configure a server instance
    * Start and stop a server instance
* Inexor Core (Client): Multi user input support
  * Assign a mouse to a instance of Inexor Core
  * Assign a keyboard to a instance of Inexor Core
* Inexor Core (Client): Split screen support
  * Inexor Flex arranges the positions of the windows of Inexor Core
  * Vertical split screen
    * Borderless window
    * First instance of Inexor Core: left side
    * Second instance of Inexor Core: right side
  * Horizontal split screen
    * Borderless window
    * First instance of Inexor Core: upper area
    * Second instance of Inexor Core: lower area
  * Monitor split screen
    * Borderless window
    * Each instance is positioned on a separate monitor

**Comment by a-teammate** [comment]
+1 
Very good summary

Just the splitscreen support should be done on one Client instance (for performance)

**Comment by Fohlen** [comment]
Restricting the `flex` server to a single instance could be done using https://nodejs.org/api/process.html#process_process_pid .. then adding a command which looks up the pid and adding an appropriate script to the `package.json` would be the way to go with `npm start && npm stop`, although shutdown via `port` is probably more desirable.

**Comment by aschaeffer** [comment]
Done in flex/master.
