### ISSUE TITLE
Create a web based console

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#386]
In order to replace the ingame console, we've to implement a web based console. The idea is to reuse the command line API we are currently building.

Each instance get it's own console, which allows to switch between different consoles. The Inexor Web Console works the same way for instances of Inexor Core Client AND Inexor Core Server.

* An publicity available Inexor Core Server can be administered using a web interface
* An Inexor Core Client shows it's own console using a transparent layer
  * If you have permissions, you can also administer local or remote server instances within an Inexor Core Client

The user interface component can be found here: https://github.com/inexor-game/ui-console

## Tasks

- [ ] The Inexor Core Client shows it's own console as transparent layer
- [ ] The Inexor Core Client shows other consoles (e.g. consoles from server instances)
- [ ] The Inexor Web Console shows the console output
- [ ] The Inexor Web Console let the user enter commands (or text)
- [ ] Inexor Flex delivers the Inexor Web Console via express
- [ ] Inexor Flex manages the console buffer for each instance
- [ ] Inexor Flex manages the execution of commands

## Console Input Handling

    Replace this by a sequence diagram!

1. [UI-Console] User enters a command
2. [UI-Console] Sends REST Request: POST /instances/:instance_id/execute { command: command }
3. [Flex] Receives REST Request: /instances/:instance_id/execute
4. [Flex] Calls CommandManager.executeCommand(instance_id, command) --> redirects output to ConsoleManager.writeBuffer(buffer)
5. [Flex] Executes yargs.commandDir('server/commands/cli/')
6. [TreeClient] Sends REST Request for command /api/v1/...
7. [Flex (2)] Receives REST Request /api/v1/... 
8. [Flex (2)] Executes Business Logic
9. [Flex (2)] Sends REST Response
10. [TreeClient] Receives REST Response
11. [Flex] output = CommandManager.executeCommand()
12. [Flex] ConsoleManager.writeBuffer(output)
13. [Flex] Sends REST Response
14. [UI-Console] Receives REST Response
15. [UI-Console] Updates the console output

## Related

* #60
